# Generated by Django 5.2.14 on 2026-05-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
